### ISSUE TITLE
JS platform: `TypeError: _sodium_init is not a function`

### ISSUE THREAD

**Issue by ForteScarlet** [ionspin/kotlin-multiplatform-libsodium#69]
Hi! When I try to call:

```kotlin
LibsodiumInitializer.initialize()
```

I got:

```
TypeError: _sodium_init is not a function
TypeError: _sodium_init is not a function
	at <global>.<unknown>(C:\home\ionspin\Projects\Future\kotlin-multiplatform-libsodium\multiplatform-crypto-libsodium-bindings\src\jsMain\kotlin\com\ionspin\kotlin\crypto\JsSodiumLoader.kt:33)
	at <global>.processTicksAndRejections(node:internal/process/task_queues:105)
```

The implementation:

```kotlin
implementation("com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.9.5")
```

**Comment by BernatCarbo** [comment]
Same here, I'm slightly confused since the issue suddenly appeared without any change.

**Comment by BernatCarbo** [comment]
@ionspin, do you have any insight about this issue?

**Comment by ionspin** [comment]
Hey, sorry I haven't had any time to look into this, and that doesn't seem to be changing in the near future. If anybody wants to do some debugging, feel free!

**Comment by kerleba** [comment]
I was able to reproduce this when the package manager installs `libsodium-sumo: 0.7.16` instead of `0.7.13` which the project expects. 

The problem is that the `libsodium-sumo-wrappers` specify the dependency as `^0.7.13` so package managers are then happy to install the newer version: https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/main/kotlin-js-store/yarn.lock#L1669

This could be solved by adding explicit dependecy on `libsodium-sumo` with the specific version it was built

**Comment by ionspin** [comment]
Thank you for looking into this and figuring out what is happening! I think better solution would be to fix the wrapper library to work with 0.8.2 like in your pull request. Do you have an idea on how to solve this with the latest version? 

Sorry for not looking into this more, I'm very limited on time I can spend on open source at the moment.

**Comment by kerleba** [comment]
I have updated https://github.com/ionspin/kotlin-multiplatform-libsodium/pull/70 to pin the 0.8.2 version.

See https://github.com/ionspin/kotlin-multiplatform-libsodium/pull/70/changes#diff-147cd3b6a6d10c7212ee46a4d697c47cdf6c1f0af7ea3b9ea8170d330656b8d9R1112 - it now explicitly requires 0.8.2 ensuring compatibility. 

I have tested locally and works well for me.

**Comment by edenman** [comment]
@ionspin can you take a look please?

**Comment by kerleba** [comment]
@ionspin would you be willing to merge https://github.com/ionspin/kotlin-multiplatform-libsodium/pull/70 to fix this issue?
